name: qt-build
 
on: push # when to trigger this. Here, on every push
jobs:
  build_and_test:
    name: "Build and test"
    strategy:
      matrix:
        os: [windows-latest,macos-13] # we build on GitHub-provided Windows and Linux images
    runs-on: ${{ matrix.os }} # use value from the matrix
    env:
         Qt_Build_Version: '5.12.12'
    steps:
     - name: "Checking for Mac"
       if: matrix.os == 'macos-13'
       run: echo 'Target Mac' && echo "Build_Target=mac" >> $GITHUB_ENV && echo "Build_Arch=clang_64" >> $GITHUB_ENV
     - name: "Checking for Windows" 
       if: matrix.os == 'windows-latest'
       run: echo 'Target Windows' && echo "Build_Target=windows" >> $GITHUB_ENV && echo "Build_Arch=msvc2017_64" >> $GITHUB_ENV      
     - name: Install Qt
       uses: jurplel/install-qt-action@v3
       with:
         version: ${{env.Qt_Build_Version}}
         arch: ${{env.Build_Arch}}
         cache: true
         setup-python: false
     - uses: actions/checkout@v4    # Actually check out the sources. GH Actions can run for events that may not require
     - uses: ruby/setup-ruby@v1
       with:
         ruby-version: '3.3.6'
         bundler-cache: true

     - name: Setup Ruby Gems
       run: cd '${{github.workspace}}/build/QT/CommandLine' && bundle install 
       # We don't need to set up the environment variable for CMake to see Qt because the install-qt-action
       # sets up the necessary variables automatically
     - name: Build FreeStick Lib
       run: cd '${{ github.workspace}}/build/QT/CommandLine' && ruby build.rb --qt=${{runner.workspace}}/${{env.Qt_Build_Version}} --target=${{env.Build_Target}}
   
